layout_spectrum: 0.1397497
typography_spectrum: 0.4217272
color:
  lightness: 0.02104472
  brandStrength: 0.6922067
  saturation: 0.8962101
  rhythmicContrast: 0.1471043
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: functionauts
