layout_spectrum: 0.1397497
name: functionauts
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
  brandColors:
    - '#201628'
    - '#000000'
    - '#5F3760'
    - '#605285'
    - '#1B0F20'
typography_spectrum: 0.3787234
